<a href="https://colab.research.google.com/github/Akshay3306/23CSBTB-27/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arry=np.array([2,5,3,7,3])
print(array)
print(type(array))


[2 5 3 7 3]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
arry=np.array([[2,5],[4,2]])
arry1=np.array([[2,5,4,2],[4,2,1,0]])
arry2=np.array([[2,5,4],[4,2,5,],[6,7,8]])
print(arry)
print(arry1)
print(arry2)

[[2 5]
 [4 2]]
[[2 5 4 2]
 [4 2 1 0]]
[[2 5 4]
 [4 2 5]
 [6 7 8]]
